- hosts: all
  tasks:
    - name: Add hosts
      include_tasks: ./templates/add_hosts.yml

    - name: Include OS-specific vars
      include_vars:
        file: "vars/{{ ansible_system | lower }}.yml"

    - name: Ensure PasswordAuthentication is disabled
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: '^#?PasswordAuthentication\s+'
        line: 'PasswordAuthentication no'
        state: present
        backrefs: yes
      become: true
      when: "'C' not in group_names"

    - name: Reload SSH service
      ansible.builtin.service:
        name: "{{ ssh_service_name }}"
        state: reloaded
      become: true
      when: "'C' not in group_names"

    - name: Install tmux and vim
      ansible.builtin.package:
        name:
          - tmux
          - git
          - curl
          - vim
          - fish
          - ripgrep
        state: present
      become: true
      when: "'C' not in group_names"

    - name: Install killall
      ansible.builtin.package:
        name:
          - psmisc
      become: true
      when:
        - "'C' not in group_names"
        - when: ansible_pkg_mgr == "apt"

    - name: Change user shell to fish
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: "{{ install_path }}/bin/fish"
      become: true
      when: "'C' not in group_names"

    - name: Install no-root setup
      include_tasks: ./templates/dotfiles.yml
